version: "2"
run:
  concurrency: 4
  tests: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - forbidigo
    - ginkgolinter
    - importas
    - ineffassign
    - misspell
    - nakedret
    - predeclared
    - unused
    - usestdlibvars
    - whitespace
  settings:
    forbidigo:
      forbid:
        - pattern: anypb.New
          msg: Do not use anypb.New; Use utils.MessageToAny instead.
    importas:
      alias:
        - pkg: k8s.io/api/apps/v1
          alias: appsv1
        - pkg: k8s.io/api/core/v1
          alias: corev1
        - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
          alias: metav1
        - pkg: k8s.io/api/batch/v1
          alias: batchv1
    misspell:
      ignore-rules:
        - kgateway
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - test/rules
      - gomock_reflect_\d*
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
  uniq-by-line: true
formatters:
  enable:
    - goimports
    - golines
  exclusions:
    generated: lax
    paths:
      - test/rules
      - gomock_reflect_\d*
      - third_party$
      - builtin$
      - examples$
