// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
)

// ExternalProviderSpecApplyConfiguration represents a declarative configuration of the ExternalProviderSpec type for use
// with apply.
type ExternalProviderSpecApplyConfiguration struct {
	Type    *apiv1alpha1.ExternalProviderType  `json:"type,omitempty"`
	Stage   *StageConfigApplyConfiguration     `json:"stage,omitempty"`
	ExtAuth *ExtAuthProviderApplyConfiguration `json:"extAuth,omitempty"`
	ExtProc *ExtProcProviderApplyConfiguration `json:"extProc,omitempty"`
}

// ExternalProviderSpecApplyConfiguration constructs a declarative configuration of the ExternalProviderSpec type for use with
// apply.
func ExternalProviderSpec() *ExternalProviderSpecApplyConfiguration {
	return &ExternalProviderSpecApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *ExternalProviderSpecApplyConfiguration) WithType(value apiv1alpha1.ExternalProviderType) *ExternalProviderSpecApplyConfiguration {
	b.Type = &value
	return b
}

// WithStage sets the Stage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Stage field is set to the value of the last call.
func (b *ExternalProviderSpecApplyConfiguration) WithStage(value *StageConfigApplyConfiguration) *ExternalProviderSpecApplyConfiguration {
	b.Stage = value
	return b
}

// WithExtAuth sets the ExtAuth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExtAuth field is set to the value of the last call.
func (b *ExternalProviderSpecApplyConfiguration) WithExtAuth(value *ExtAuthProviderApplyConfiguration) *ExternalProviderSpecApplyConfiguration {
	b.ExtAuth = value
	return b
}

// WithExtProc sets the ExtProc field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExtProc field is set to the value of the last call.
func (b *ExternalProviderSpecApplyConfiguration) WithExtProc(value *ExtProcProviderApplyConfiguration) *ExternalProviderSpecApplyConfiguration {
	b.ExtProc = value
	return b
}
