// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
)

// PlacementApplyConfiguration represents a declarative configuration of the Placement type for use
// with apply.
type PlacementApplyConfiguration struct {
	Name     *apiv1alpha1.FilterStageName `json:"name,omitempty"`
	Priority *int32                       `json:"priority,omitempty"`
}

// PlacementApplyConfiguration constructs a declarative configuration of the Placement type for use with
// apply.
func Placement() *PlacementApplyConfiguration {
	return &PlacementApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *PlacementApplyConfiguration) WithName(value apiv1alpha1.FilterStageName) *PlacementApplyConfiguration {
	b.Name = &value
	return b
}

// WithPriority sets the Priority field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Priority field is set to the value of the last call.
func (b *PlacementApplyConfiguration) WithPriority(value int32) *PlacementApplyConfiguration {
	b.Priority = &value
	return b
}
