// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
)

// StageConfigApplyConfiguration represents a declarative configuration of the StageConfig type for use
// with apply.
type StageConfigApplyConfiguration struct {
	Name   *apiv1alpha1.FilterStageName `json:"name,omitempty"`
	Weight *int32                       `json:"weight,omitempty"`
}

// StageConfigApplyConfiguration constructs a declarative configuration of the StageConfig type for use with
// apply.
func StageConfig() *StageConfigApplyConfiguration {
	return &StageConfigApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *StageConfigApplyConfiguration) WithName(value apiv1alpha1.FilterStageName) *StageConfigApplyConfiguration {
	b.Name = &value
	return b
}

// WithWeight sets the Weight field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Weight field is set to the value of the last call.
func (b *StageConfigApplyConfiguration) WithWeight(value int32) *StageConfigApplyConfiguration {
	b.Weight = &value
	return b
}
