// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	gentype "k8s.io/client-go/gentype"

	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/applyconfiguration/api/v1alpha1"
	v1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
	typedapiv1alpha1 "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/typed/api/v1alpha1"
)

// fakeExternalProviders implements ExternalProviderInterface
type fakeExternalProviders struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.ExternalProvider, *v1alpha1.ExternalProviderList, *apiv1alpha1.ExternalProviderApplyConfiguration]
	Fake *FakeGatewayV1alpha1
}

func newFakeExternalProviders(fake *FakeGatewayV1alpha1, namespace string) typedapiv1alpha1.ExternalProviderInterface {
	return &fakeExternalProviders{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.ExternalProvider, *v1alpha1.ExternalProviderList, *apiv1alpha1.ExternalProviderApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("externalproviders"),
			v1alpha1.SchemeGroupVersion.WithKind("ExternalProvider"),
			func() *v1alpha1.ExternalProvider { return &v1alpha1.ExternalProvider{} },
			func() *v1alpha1.ExternalProviderList { return &v1alpha1.ExternalProviderList{} },
			func(dst, src *v1alpha1.ExternalProviderList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ExternalProviderList) []*v1alpha1.ExternalProvider {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ExternalProviderList, items []*v1alpha1.ExternalProvider) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
