// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	gentype "k8s.io/client-go/gentype"

	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/applyconfiguration/api/v1alpha1"
	v1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
	typedapiv1alpha1 "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/typed/api/v1alpha1"
)

// fakeGatewayExtensionPolicies implements GatewayExtensionPolicyInterface
type fakeGatewayExtensionPolicies struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.GatewayExtensionPolicy, *v1alpha1.GatewayExtensionPolicyList, *apiv1alpha1.GatewayExtensionPolicyApplyConfiguration]
	Fake *FakeGatewayV1alpha1
}

func newFakeGatewayExtensionPolicies(fake *FakeGatewayV1alpha1, namespace string) typedapiv1alpha1.GatewayExtensionPolicyInterface {
	return &fakeGatewayExtensionPolicies{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.GatewayExtensionPolicy, *v1alpha1.GatewayExtensionPolicyList, *apiv1alpha1.GatewayExtensionPolicyApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("gatewayextensionpolicies"),
			v1alpha1.SchemeGroupVersion.WithKind("GatewayExtensionPolicy"),
			func() *v1alpha1.GatewayExtensionPolicy { return &v1alpha1.GatewayExtensionPolicy{} },
			func() *v1alpha1.GatewayExtensionPolicyList { return &v1alpha1.GatewayExtensionPolicyList{} },
			func(dst, src *v1alpha1.GatewayExtensionPolicyList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.GatewayExtensionPolicyList) []*v1alpha1.GatewayExtensionPolicy {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.GatewayExtensionPolicyList, items []*v1alpha1.GatewayExtensionPolicy) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
