// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"

	applyconfigurationapiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/applyconfiguration/api/v1alpha1"
	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
	scheme "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/scheme"
)

// ExternalProvidersGetter has a method to return a ExternalProviderInterface.
// A group's client should implement this interface.
type ExternalProvidersGetter interface {
	ExternalProviders(namespace string) ExternalProviderInterface
}

// ExternalProviderInterface has methods to work with ExternalProvider resources.
type ExternalProviderInterface interface {
	Create(ctx context.Context, externalProvider *apiv1alpha1.ExternalProvider, opts v1.CreateOptions) (*apiv1alpha1.ExternalProvider, error)
	Update(ctx context.Context, externalProvider *apiv1alpha1.ExternalProvider, opts v1.UpdateOptions) (*apiv1alpha1.ExternalProvider, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, externalProvider *apiv1alpha1.ExternalProvider, opts v1.UpdateOptions) (*apiv1alpha1.ExternalProvider, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.ExternalProvider, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.ExternalProviderList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.ExternalProvider, err error)
	Apply(ctx context.Context, externalProvider *applyconfigurationapiv1alpha1.ExternalProviderApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.ExternalProvider, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, externalProvider *applyconfigurationapiv1alpha1.ExternalProviderApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.ExternalProvider, err error)
	ExternalProviderExpansion
}

// externalProviders implements ExternalProviderInterface
type externalProviders struct {
	*gentype.ClientWithListAndApply[*apiv1alpha1.ExternalProvider, *apiv1alpha1.ExternalProviderList, *applyconfigurationapiv1alpha1.ExternalProviderApplyConfiguration]
}

// newExternalProviders returns a ExternalProviders
func newExternalProviders(c *GatewayV1alpha1Client, namespace string) *externalProviders {
	return &externalProviders{
		gentype.NewClientWithListAndApply[*apiv1alpha1.ExternalProvider, *apiv1alpha1.ExternalProviderList, *applyconfigurationapiv1alpha1.ExternalProviderApplyConfiguration](
			"externalproviders",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.ExternalProvider { return &apiv1alpha1.ExternalProvider{} },
			func() *apiv1alpha1.ExternalProviderList { return &apiv1alpha1.ExternalProviderList{} },
		),
	}
}
