// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"

	applyconfigurationapiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/applyconfiguration/api/v1alpha1"
	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
	scheme "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/scheme"
)

// GatewayExtensionPoliciesGetter has a method to return a GatewayExtensionPolicyInterface.
// A group's client should implement this interface.
type GatewayExtensionPoliciesGetter interface {
	GatewayExtensionPolicies(namespace string) GatewayExtensionPolicyInterface
}

// GatewayExtensionPolicyInterface has methods to work with GatewayExtensionPolicy resources.
type GatewayExtensionPolicyInterface interface {
	Create(ctx context.Context, gatewayExtensionPolicy *apiv1alpha1.GatewayExtensionPolicy, opts v1.CreateOptions) (*apiv1alpha1.GatewayExtensionPolicy, error)
	Update(ctx context.Context, gatewayExtensionPolicy *apiv1alpha1.GatewayExtensionPolicy, opts v1.UpdateOptions) (*apiv1alpha1.GatewayExtensionPolicy, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, gatewayExtensionPolicy *apiv1alpha1.GatewayExtensionPolicy, opts v1.UpdateOptions) (*apiv1alpha1.GatewayExtensionPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.GatewayExtensionPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.GatewayExtensionPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.GatewayExtensionPolicy, err error)
	Apply(ctx context.Context, gatewayExtensionPolicy *applyconfigurationapiv1alpha1.GatewayExtensionPolicyApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.GatewayExtensionPolicy, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, gatewayExtensionPolicy *applyconfigurationapiv1alpha1.GatewayExtensionPolicyApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.GatewayExtensionPolicy, err error)
	GatewayExtensionPolicyExpansion
}

// gatewayExtensionPolicies implements GatewayExtensionPolicyInterface
type gatewayExtensionPolicies struct {
	*gentype.ClientWithListAndApply[*apiv1alpha1.GatewayExtensionPolicy, *apiv1alpha1.GatewayExtensionPolicyList, *applyconfigurationapiv1alpha1.GatewayExtensionPolicyApplyConfiguration]
}

// newGatewayExtensionPolicies returns a GatewayExtensionPolicies
func newGatewayExtensionPolicies(c *GatewayV1alpha1Client, namespace string) *gatewayExtensionPolicies {
	return &gatewayExtensionPolicies{
		gentype.NewClientWithListAndApply[*apiv1alpha1.GatewayExtensionPolicy, *apiv1alpha1.GatewayExtensionPolicyList, *applyconfigurationapiv1alpha1.GatewayExtensionPolicyApplyConfiguration](
			"gatewayextensionpolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.GatewayExtensionPolicy { return &apiv1alpha1.GatewayExtensionPolicy{} },
			func() *apiv1alpha1.GatewayExtensionPolicyList { return &apiv1alpha1.GatewayExtensionPolicyList{} },
		),
	}
}
